[build]
  functions="functions/"
  environment = { NODE_VERSION = "20.15.0" }
  command = "npm install --force && npm run build"

[dev]
  functions="functions/"

[functions]
  external_node_modules = ['pg']

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200